apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Fastify Demo App
  description: A Demo App with examples of how Fastify API is used..
  
  annotations:
   github.com/project-slug: prakash-coder13/fastify-demo
   backstage.io/techdocs-ref: dir:.
spec:
  type: API
  owner: prakash-coder13@github.com
  lifecycle: poc
